sudo: false

addons:
  apt:
    packages:
      - ruby
      - libffi-dev
      - python-dev
      - graphviz
      - gcc
      - libssl-dev

language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt
  - pip install coverage

before_script:
  - python utils/db_create.py

script: coverage run -m unittest discover tests/
