sudo: false

addons:
  apt:
    packages:
      - ruby
      - libffi-dev
      - python-dev
      - graphviz
      - gcc
      - libssl-dev

language: python

python:
  - 2.7

install:
  - pip install -r requirements.txt

before_script:
  - python utils/db_create.py

script: python tests/full_tests.py && python tests/api_tests.py
