addons:
  apt:
    packages:
      - ruby
      - libffi-dev
      - python-dev
      - graphviz
      - gcc
      - libssl-dev

language: python

matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
    - os: osx
      language: python
      before_install:
        - brew update
        - brew install gcc graphviz ruby
        - brew install libmagic
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"

  allow_failures:
    - os: osx
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage==4.3
  - pip install codeclimate-test-reporter

before_script:
  - python utils/db_create.py

after_success:
  - codeclimate-test-reporter

script: coverage run --omit flask/* -m unittest discover tests/
