addons:
  apt:
    packages:
      - ruby
      - libffi-dev
      - python-dev
      - graphviz
      - gcc
      - libssl-dev

language: python

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: false
      dist: trusty
    - os: osx
      language: python
      before_install:
        - brew update
        - brew install gcc graphviz ruby
        - brew install libmagic
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"

  allow_failures:
    - os: osx
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codeclimate-test-reporter
  - echo "import coverage;coverage.process_startup()" > sitecustomize.py
  - echo "[run]\nconcurrency = multiprocessing\nbranch = true\nparallel = True" > .coveragerc

before_script:
  - python utils/db_create.py

after_success:
  - coverage combine
  - codeclimate-test-reporter

script: coverage run --parallel-mode -m unittest discover tests/
